export const REQUEST_PERSONAL_CHAT_SUCCESS = 'REQUEST_PERSONAL_CHAT_SUCCESS';
export const REQUEST_PERSONAL_CHAT_FAIL = 'REQUEST_PERSONAL_CHAT_FAIL';

export const GET_PERSONAL_CHAT_REQUEST_SUCCESS = 'GET_PERSONAL_CHAT_REQUEST_SUCCESS';
export const GET_PERSONAL_CHAT_REQUEST_FAIL = 'GET_PERSONAL_CHAT_REQUEST_FAIL';

export const REPLY_PERSONAL_CHAT_REQUEST_SUCCESS = 'REPLY_PERSONAL_CHAT_REQUEST_SUCCESS';
export const REPLY_PERSONAL_CHAT_REQUEST_FAIL = 'REPLY_PERSONAL_CHAT_REQUEST_FAIL';