export const GET_MY_GROUP_PROFILE_SUCCESS = 'GET_MY_GROUP_PROFILE_SUCCESS';
export const GET_MY_GROUP_PROFILE_FAIL = 'GET_MY_GROUP_PROFILE_FAIL';

export const ADD_GROUP_PROFILE_SUCCESS = 'ADD_GROUP_PROFILE_SUCCESS';
export const ADD_GROUP_PROFILE_FAIL = 'ADD_GROUP_PROFILE_FAIL';

export const LOAD_ALL_GROUP_PROFILE_SUCCESS = 'LOAD_ALL_GROUP_PROFILE_SUCCESS';
export const LOAD_ALL_GROUP_PROFILE_FAIL = 'LOAD_ALL_GROUP_PROFILE_FAIL';

export const CHANGE_GROUP_PROFILE_SUCCESS = 'CHANGE_GROUP_PROFILE_SUCCESS';
export const CHANGE_GROUP_PROFILE_FAIL = 'CHANGE_GROUP_PROFILE_FAIL';

export const DELETE_GROUP_PROFILE_SUCCESS = 'DELETE_GROUP_PROFILE_SUCCESS';
export const DELETE_GROUP_PROFILE_FAIL = 'DELETE_GROUP_PROFILE_FAIL';

export const LOAD_CANDIDATE_PROFILE_SUCCESS = 'LOAD_CANDIDATE_PROFILE_SUCCESS';
export const LOAD_CANDIDATE_PROFILE_FAIL = 'LOAD_CANDIDATE_PROFILE_FAIL';

export const CLEAR_CANDIDATE_PROFILE = 'CLEAR_CANDIDATE_PROFILE';