export const LOAD_GROUP_REQUEST_SUCCESS = 'LOAD_GROUP_REQUEST_SUCCESS';
export const LOAD_GROUP_REQUEST_FAIL = 'LOAD_GROUP_REQUEST_FAIL';

export const REQUEST_GROUP_CHAT_SUCCESS = 'REQUEST_GROUP_CHAT_SUCCESS';
export const REQUEST_GROUP_CHAT_FAIL = 'REQUEST_GROUP_CHAT_FAIL';
