export const LOAD_PERSONAL_REQUEST_SUCCESS = 'LOAD_PERSONAL_REQUEST_SUCCESS';
export const LOAD_PERSONAL_REQUEST_FAIL = 'LOAD_PERSONAL_REQUEST_FAIL';

export const REQUEST_PERSONAL_CHAT_SUCCESS = 'REQUEST_PERSONAL_CHAT_SUCCESS';
export const REQUEST_PERSONAL_CHAT_FAIL = 'REQUEST_PERSONAL_CHAT_FAIL';
