export const LOAD_NOTICE_FAIL = "LOAD_NOTICE_FAIL";
export const LOAD_NOTICE_SUCCESS = "LOAD_NOTICE_SUCCESS";

export const GET_NOTICE_ALARM_SUCCESS = 'GET_NOTICE_ALARM_SUCCESS';
export const GET_NOTICE_ALARM_FAIL = 'GET_NOTICE_ALARM_FAIL';
