export const REQUEST_GROUP_CHAT_SUCCESS = 'REQUEST_GROUP_CHAT_SUCCESS';
export const REQUEST_GROUP_CHAT_FAIL = 'REQUEST_GROUP_CHAT_FAIL';

export const GET_GROUP_CHAT_REQUEST_SUCCESS = 'GET_GROUP_CHAT_REQUEST_SUCCESS';
export const GET_GROUP_CHAT_REQUEST_FAIL = 'GET_GROUP_CHAT_REQUEST_FAIL';

export const REPLY_GROUP_CHAT_REQUEST_SUCCESS = 'REPLY_GROUP_CHAT_REQUEST_SUCCESS';
export const REPLY_GROUP_CHAT_REQUEST_FAIL = 'REPLY_GROUP_CHAT_REQUEST_FAIL';