spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379

  # kafka:
  #   bootstrap-servers: localhost:9092
  #   consumer:
  #     bootstrap-servers: localhost:9092
  #     group-id: my-group
  #     auto-offset-reset: earliest
  #   producer:
  #     bootstrap-servers: localhost:9092
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      maxFileSize: 500MB
      maxRequestSize: 500MB

  config:
    import:
      - aws.yml
      - email.yml
      - chat.yml
      - push.yml
      - debezium.yml