export const ENROLL_PHONE_SUCCESS = "ENROLL_PHONE_SUCCESS";
export const ENROLL_PHONE_FAIL = "ENROLL_PHONE_FAIL";
export const VERIFY_PHONE_SUCCESS = "VERIFY_PHONE_SUCCESS";
export const VERIFY_PHONE_FAIL = "VERIFY_PHONE_FAIL";